import "./globals.scss";
import { ProductProvider } from '../context/Mycontext';


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css" />

      </head>
      <body>
        <ProductProvider>
       
          {children}
        </ProductProvider>
      </body>
    </html>
  );
}
