import "./globals.scss";
import Headers from "../app/common/header";
import { CartProvider } from "../context/cart_context";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      </head>
      <body>
        <CartProvider>
       
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
